import Head from "next/head";
import Image from "next/image";
import CardMembers from "../components/CardMembers";
import CircleMembers from "../components/CircleMembers";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Villages from "../components/Villages";
 

const HeadTag = () => (
    <Head>
        <title>Akatsuki</title>
        <meta name="description" content="Generated by create next app" />
    </Head>
);

export default function Home() {
    return (
        <>
            <HeadTag />
            <Header />

            <div className="container">
                <Villages />
                <CircleMembers memberType="UNOFFICIAL" />
                <CardMembers />
            </div>
            <Footer />
        </>
    );
}
